- src/digital_io.rs
The DUT UART lines were shown as off in the interface even though they were on.
Controlling them did hower do the right thing.
> digital_io: fix wrong initial state for inverted pins

- web/src/DashboardDut.tsx
This looks like some copy-paste-error.
With this fix the naming should be right.
> Dashboard: Fix Typo in RX Enable

- openapi.yaml
- src/dut_power.rs
- src/ui/power_screen.rs
… and `OffFloating` special
The voltage measurement on the LXA TAC powerboard is quite high impedance. This is rather nice, as it means we do not load the power supply etc. What's not nice is that it means the measurement is very susceptible to noise, e.g. when no DUT is connected.
This has lead to some confusion in the past.
Just make the low-impedance `OffDischarge` the new `Off` and make `OffFloating` the "I know what I am doing" special case.
Things to do before un-marking as WIP:
> dut_power: make OffDischarge the default Off state

- src/web.rs
The `req` parameter is unused in this specific `.get` handler leading to a warning being generated on build.
> tacd: web: fix unused variable warning

- .github/workflows/tacd-daemon.yaml
- .github/workflows/tacd-webui.yaml
Add GitHub Workflows that for the …
* … tacd daemon …
* … runs cargo check to make sure that a Pull Request is buildable.
* … runs cargo fmt to make sure the PR is well formatted.
* … runs cargo clippy to add annotations to the PR about possible improvements.
* … runs cargo test to execute the (currently rather small) test suite.
* … tacd web interface …
* … run npx prettiert to check if the typescript code base is well formatted.
* … run npm run build to check if the web interface is buildable.
I can think of some more interesting actions, but this should be a good starting point.
The current codebase contains enough … *errr* … test cases for these workflows to generate some output.
> Add GitHub Workflows for Deamon and Web UI

- src/adc/iio/stub.rs
- src/dut_power.rs
Short transients on these values will not result in damage to the TAC or DUT, so they should be filtered out to prevent the DUT from being turned of due to EMI or inrush current.
Things to do before un-marking as WIP:
> dut_power: add median filter to over/under voltage/current detection

- Cargo.lock
- Cargo.toml
- openapi.yaml
- src/dbus.rs
- src/dbus/networkmanager/mod.rs
- src/digital_io.rs
- src/digital_io/gpio/demo_mode.rs
- src/dut_power.rs
- src/led.rs
- src/led/demo_mode.rs
- src/led/extras.rs
- src/main.rs
- src/regulators.rs
- src/ui.rs
- src/ui/draw_fb.rs
- src/ui/screens.rs
- src/ui/screens/dig_out.rs
- src/ui/screens/iobus.rs
- src/ui/screens/power.rs
- src/ui/screens/rauc.rs
- src/ui/screens/reboot.rs
- src/ui/screens/screensaver.rs
- src/ui/screens/system.rs
- src/ui/screens/uart.rs
- src/ui/screens/usb.rs
- src/ui/widgets.rs
Hardware generations
-----------------------------
There is a new batch of LXA TAC devices with a slightly different set of hardware features (**Gen 2**).
Here is an overview of the current hardware generations:
- **Gen 1 Stock**
- 128px x 64px OLED screen
- No LED indicators on the top side of the device.
- **Gen 1 LCD**
- Like **Gen 1 Stock** but retrofitted with a 240px x 240px LCD screen
- All of the **Gen 1 Stock** devices should be modified to this state
- **Gen 2**
- 240px x 240px LCD screen
- LED indicators on the top side of the device
With this PR applied only hardware generations **Gen 1 LCD** and **Gen 2** are supported. Support for **Gen 1 Stock** is dropped.
Related pull requests
----------------------------
- `tacd` This PR was modified to be built upon the mega cleanup PR …
> Support LXA TAC Gen 2 devices (tacd)

- Cargo.lock
- web/package-lock.json
Update dependencies via
```bash
$ cargo update
$ cd web
$ npm update
```
With the exception of the rust dependency `winnow` which was manually limited to version `0.4.1` instead of the newest upstream release `0.4.6` due to a minimum rust [version bump](https://github.com/winnow-rs/winnow/commit/3944ecec24ef5d485b2516b1b19855b7241e6405) after `0.4.1` which is incompatible with the current rust version in `meta-lxatac`:
```
$ bitbake tacd
| error: package `winnow v0.4.5` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.63.0
| WARNING: exit code 101 from a shell command.
```
A `langdale` -> `mickledore` yocto update will bring a sufficiently new rust version to update `winnow`.
-------------------
- ~~This PR is …
> Update rust and node dependencies

- src/ui/screens/usb.rs
- src/usb_hub.rs
The power state of the USB Hub ports may be changed by the `tacd` or by some other program, e.g. `uhubctl`.
We do not (yet) have an interface to be notified of changes to the port, so we use periodic polling instead.
Up until now we've just accepted that a `topic.set()` triggered by the periodic polling triggers a write to the port with the state it just read.
This does however result in glitches when a new value is set e.g. via the API while the polling task is reading the current state, resulting in the state being reset to the previous state.
This issue is triggered by the scripts used to stress the TAC during an EMI test.
----------------------------
> usb_hub: split powered state and request to prevent glitches

- .github/workflows/tacd-webui.yaml
- README.md
- web/package.json
- web/public/index.html
- web/src/ApiDocs.tsx
- web/src/ConfigEditor.tsx
- web/src/MqttComponents.tsx
- web/src/TacComponents.tsx
- web/src/index.css
- web/src/index.tsx
- web/src/mqtt.ts
We've recently started noticing failing `prettier` runs in our CI (See #29).
This is due to a new `prettier` release that changes some of the formatting rules.
The version of `prettier` (and thus the formatting rules) that `npx` selects depends on the node version running on the development machine / CI VM, due to the required node version changing with the `prettier` 3.0 release.
This is bound to cause confusion. Instead specify the `prettier` version manually and as strictly as possible to make sure the formatting rules are consistent.
This breaks `prettier` on nodejs installed from Debian bullseye's apt repositories.
> web: prettier: (explicitly) upgrade to version 3.0.1

- web/src/DashboardDut.tsx
- web/src/MqttComponents.tsx
As of now the y-Axis auto-scales to match the values in the plot. This means it expands the axis to arbitrarily small values, making
every bit of ADC noise look huge (even though it isn't).
Specify explicit ranges to snap to instead. The selected values are not completely random. The DUT voltage ranges for example are choosen just above typical supply voltages (5V, 12V, 24V, 48V).
Without this PR (simulated but somewhat realistic values):
With this PR (simulated but somewhat realistic values):
> web: MqttComponents: Snap MqttChart y-axis dimensions to a list of fixed values

- src/regulators.rs
The regulator names with underscores instead of dashes do not match the schema that should be used in upstream devicetrees.
---------------
This PR depends on the following other PRs which require coordination:
> regulators: change regulator names to those in new devicetrees

- openapi.yaml
- src/backlight.rs
- src/backlight/demo_mode.rs
- src/main.rs
- src/ui.rs
- src/ui/screens/screensaver.rs
There is no strict requirement for dimming the backlight.
The power draw is not significant and the lifetime of the LEDs should also not be an issue.
It just feels right to have the dimming.
We could also make the dimming configurable later on if we see a need.
> backlight: dim the backlight when in screensaver mode

- src/digital_io.rs
- src/digital_io/gpio/demo_mode.rs
- src/digital_io/gpio/test.rs
- src/iobus.rs
- src/main.rs
- src/regulators.rs
- src/ui/screens.rs
- src/ui/screens/iobus.rs
- src/ui/screens/iobus_health.rs
- web/src/App.tsx
- web/src/TacComponents.tsx
This should make troubleshooting easier in case of a short-circuit or overload on the IOBus bus.
----------
> iobus: display power supply overload notifications  

- openapi.yaml
- src/temperatures.rs
- src/ui/screens.rs
- src/ui/screens/overtemperature.rs
- web/src/App.tsx
- web/src/TacComponents.tsx
Add warning on the LCD …
… and web interface if the LXA TAC is running hot.
> temperatures: display over temperature notifications

- src/adc.rs
- src/adc/iio/demo_mode.rs
- src/adc/iio/hardware.rs
- src/adc/iio/test.rs
- src/digital_io/gpio/demo_mode.rs
- src/dut_power.rs
- src/iobus.rs
- src/regulators.rs
- src/usb_hub.rs
This PR adds buffering support to the powerboard ADC. The main benefit of this change is that voltage and current samples are now taken at the exact same point int time, enabling better instantaneous power measurements.
This feature relies on kernel support for buffering in the powerboard ADC and a fix to `libiio` to allow enabling the buffer for the ADC, both of which are not currently included in `meta-lxatac`.
----------
> adc: iio: hardware: add buffering support to the powerboard ADC

- src/digital_io/gpio/demo_mode.rs
- src/digital_io/gpio/test.rs
- src/dut_power.rs
This PR improves the EMI performance of the TAC (at least when measuring the emissions on pins of the IOBus port in isolation).
How can that be you ask? The `VCC_IO` supply line powering all of the SoC's GPIO pins is necessarily affected by high frequency switching of e.g. the RGMII and eMMC lines. This results in GPIOs that are actively driven high also containing said noise.
This PR makes it so that the lines are never driven high by the SoC, relying instead on pull-up resistors on the power board.
But the `DUT_PWR_EN` and `DUT_PWR_DISCH` don't leave the device, they only go to the flat flex connector to the power board, I hear you ask. How can they couple out of the IOBus connector?
It looks like the noise couples onto the IOBus signal lines that are right next to the GPIOs on the flat …
> dut_power: make GPIOs open drain

- src/led/extras.rs
The latest `cargo clippy` learned a new trick to optimize the construction of Strings and will not give us green CI builds before we adapt to it.
- Does this make a difference in this case performance wise? No
- Does this make cargo clippy happy? Yes
So let's do it.
> led: extras: fix cargo clippy complaining about String construction

- openapi.yaml
- src/adc/iio/demo_mode.rs
- src/main.rs
- src/ui/screens.rs
- src/ui/screens/usb.rs
- src/ui/screens/usb_overload.rs
- src/usb_hub.rs
- web/src/App.tsx
- web/src/TacComponents.tsx
Add warning on the LCD …
… and web interface if the LXA TAC' USB ports are overloaded.
>  usb: display power supply overload notifications

- src/ui/screens.rs
- src/ui/screens/power_fail.rs
- web/src/App.tsx
- web/src/TacComponents.tsx
Add notification on the LCD …
… and web interface if the LXA TAC's DUT Power supply shut off due to e.g. an overcurrent or overvoltage event.
> dut_pwr: display notifcations on power failure

- .github/workflows/tacd-daemon.yaml
The checks performed by running cargo check are a subset of what cargo clippy checks for (as indicated by cargo clippy [using cargo check in the background]):
https://github.com/rust-lang/rust-clippy/blob/c154754b74577906c5d55d57f7daeff02d6a33e7/src/main.rs#L59-L105
Running both is thus a waste of CPU cycles. Run cargo clippy only.
> ci: tacd: use only cargo clippy and not cargo check as well

- src/main.rs
- src/ui.rs
- src/ui/screens.rs
As of now the `tacd` prints a "Welcome!" message on the LCD and then goes on to setting up the remaining hardware units.
If the setup of any of the peripherals fails the `tacd` just crashes and no message is printed on the LCD to inform the user.
Instead print a generic (and thus not too helpful message) to give some indication of what is going on:
We can not fit much more on the screen, so the user has to check the systemd journal if the actually want to know what's wrong.
> tacd: show message on screen if hardware setup failed

- .github/workflows/tacd-daemon.yaml
- Cargo.lock
- Cargo.toml
- deny.toml
- src/dbus/networkmanager/devices.rs
- src/dbus/rauc/mod.rs
We should make sure the tacd at least builds using the rust toolchain used in meta-lxatac.
As we are currently a bit in between chairs when it comes to Yocto versions.
We should thus test for langdale (1.63), mickledore (1.68) and nanbield (1.70).
Also throw in a nightly build for good measure.
> ci: tacd: run basic cargo check against different rust versions

- src/dbus.rs
- src/dbus/networkmanager/mod.rs
- src/dbus/rauc/mod.rs
- src/iobus.rs
- src/journal.rs
- src/temperatures.rs
- src/ui/buttons.rs
- src/ui/display.rs
- src/usb_hub.rs
- src/watchdog.rs
This makes sure we get dead code warnings about unused imports, which we do not get when using the global `pub`.
Also fix said warnings that came up.
> tacd: set appropriate pub(super) scopes for demo mode import hacks

- src/dbus/networkmanager.rs
- src/dbus/networkmanager/devices.rs
The main cause of the issue was that we did not honor the following section in the NetworkManager [DBus API documentation](https://networkmanager.dev/docs/api/latest/gdbus-org.freedesktop.NetworkManager.Device.html#gdbus-property-org-freedesktop-NetworkManager-Device.Ip4Config):
>  The "Ip4Config" property
>
>  Object path of the Ip4Config object describing the configuration of the device. Only valid when the device is in the NM_DEVICE_STATE_ACTIVATED state.
This meant however that we need to keep track of state property changes and changes inside the referenced `Ip4Config` object at the same time.
The easiest way to do so was to re-write the code in a `async`/`.await`-y way.
Also update the link and speed status updates while at it, so we do not have two completely different approaches …
> dbus: networkmanager: fix IPv4 addresses not updating when link was down

- src/ui.rs
The first hardware samples of LXA TACs with status LEDs showed them to be far to bright. Since then we have reduced the current through the "normal" (non-pwm) status LEDs by a factor of `33` in hardware. The brightness of the pwm LEDs was only reduced in hardware by a factor of `7.5`. This allows us to still make them light up quite brightly if we want them to.
In the idle state their brightness should however match the brightness of the other LEDs.
Dim them in software by a factor of `33/7.5 = 4.4`.
> ui: reduce idle brightness of the status led

- src/dbus/rauc.rs
- src/dbus/rauc/update_channels.rs
Fix two issues regarding notifications and RAUC slots:
- If the not-booted slot is marked as bad, either due to too many boot failures or manual intervention, it should not be considered when displaying _"there_ is a newer OS image in the other boot slot, reboot to use it"_ messages, as rebooting will indeed not use it.
- A bad image in the other slot should also not be considered when determining if an update is available¹.
> rauc: only consider good slots for update and reboot notifications

- web/src/App.tsx
- web/src/Setup.tsx
- web/src/TacComponents.tsx
Previously the `tacd` presented every new user with a choice between two setup methods:
The "custom bundle" was however not yet implemented and only shows a respective message when selected.
I think the custom bundle method can be integrated into the normal wizard flow once we implement it, so there is no need to keep the selection page.
I've also added a bit more description text to each wizard page. See the screenshots below for reference:
or try it out yourself:
```bash
$ rm demo_files/srv/tacd/state.json # state file in git that turns setup mode off. Remove it
$ cd web
$ npm install .
$ npm run build
$ cd -
$ cargo run --features=demo_mode --no-default-features
```
> web: setup: Simplify the setup wizard and other cleanups

- demo_files/srv/tacd/state.json
- openapi.yaml
- src/broker/topic.rs
- src/dbus/rauc.rs
- src/digital_io.rs
- src/ui/screens/setup.rs
- src/ui/screens/system.rs
- web/src/Setup.tsx
- web/src/TacComponents.tsx
Phoning home for software updates without asking for any kind of consent is bad practice and (rightfully) breaks user's trust.
So we shouldn't do it.
1) Add an endpoint to the `tacd`'s API that is persisted to disk and configures wether there should be polling for updates.
2) Add a page to the setup wizard that asks if the user wants to poll for updates.
3) Add a "Poll for updates yes/no" toggle to the Updating overview in the TAC Dashboard. And integrate the "should poll" information into the other widgets
The setup wizard page:
The dashboard panel when update polling is enabled:
The dashboard panel when update polling is disabled (and its effect on the "Channel Enabled" and "Channel Polling Interval" table columns):
---------------
This PR is based on another PR …
> Ask the user for consent before polling for updates online

- web/src/TacComponents.tsx
This fixes the "Your LXA TAC is overheating" and "One of the USB ports is overloaded" error messages being shown when the web interface loses the connection to the TAC:
This replaces #38, which tried to solve these errors in a way that felt more "correct" to me back then but cause lots of issues around the web interface that would need fixing.
> web: TacComponents: fix wrong notifications on disconnect

- web/src/SettingsLabgrid.tsx
- web/src/Setup.tsx
This PR addresses some user feedback we got from our early access testers:
* Do not display the labgrid configurations with yaml-highlighting, since the Jinja2 in there causes spurious syntax errors.
* Add a note on the completion of the labgrid configuration to the wizard.
> web: labgrid configuration

- web/src/Setup.tsx
When polling for updates we want to transmit some information about the device back to our servers.
(This is intended for us to better understand how the updates progress in a feet of devices.)
We want to allow the user to make an informed decision when enabling updates, if they want to give consent to this behavior.
> web: setup: Inform user about data sent when polling for updates

- src/backlight.rs
- src/broker/mqtt_conn.rs
- src/dbus/networkmanager.rs
- src/led.rs
Nightly rust has learned some new tricks to detect dead code and unused imports, which is quite cool.
A bit less cool is that this makes out CI runs fail right now. See [this one](https://github.com/linux-automation/tacd/actions/runs/8019854353/job/21908471258?pr=58) from PR #58 for example.
Fix these new errors by making some imports conditional and removing others.
> Fix cargo check errors that were added in nightly cargo

- src/ui/display.rs
- src/ui/screens.rs
- src/ui/screens/dig_out.rs
- src/ui/screens/help.rs
- src/ui/screens/iobus.rs
- src/ui/screens/iobus_health.rs
- src/ui/screens/locator.rs
- src/ui/screens/overtemperature.rs
- src/ui/screens/power.rs
- src/ui/screens/power_fail.rs
- src/ui/screens/reboot.rs
- src/ui/screens/screensaver.rs
- src/ui/screens/system.rs
- src/ui/screens/uart.rs
- src/ui/screens/update_available.rs
- src/ui/screens/update_installation.rs
- src/ui/screens/usb.rs
- src/ui/screens/usb_overload.rs
- src/ui/widgets.rs
This adds a little legend on the right of the screen (where the two buttons are) that tells the user what which button does what:
> ui: add button labels that tell the user which button does what

- src/broker/persistence.rs
This makes it so that a `tacd` will not fail to start if it encounters a state file that was written by a newer `tacd` version.
This means we actually have to use the versioning scheme we already have when a new persistence key e.g. has security implications that may not be lost in e.g. a new -> old -> new cycle.
Once such a change occurs we have the option to:
- Increment the `format_version` field in the state file and make older `tacd`s fail to start that way.
- Start writing changes to a new state file `/srv/tacd/state-v2.json` and also read from there if it exists, but fall back to the current path if it does not. This means old tacds keep reading the file they created and a new tacd will read from there and migrate.
But that's a problem for future us.
Right now just make sure that …
> broker: persistence: downgrade unknown keys in state file from err to warn

- src/ui/screens/help.rs
Showing users the help (aka quick-start) screen has shown that it's not
clear to everyone that they have to long-press the lower button to
actually switch to the next page of the help.
This change adds an explicit call-to-action to long-press the lower
button to the first page of help.
And afterwards explains what this has done.
This makes the help one page longer - but hopefully helps users discover
the long-press feature a little quicker.
To be merged after #56 .
> ui: help: Start first screen with a call to long-press 

- src/digital_io/gpio/test.rs
- src/dut_power.rs
This solves a problem we see with some DUTs and DUT power supplies where the DUT refuses to turn back on due to e.g. a persistent `PolarityInversion` error.
These errors are caused by leakage currents from the DUT power supply interfering with our high impedance voltage measurement. These currents result in actual measurable voltages on the DUT power switch output pins, which are measured by the ADC and interpreted as erroneous.
This PR ignores voltage measurements that would normally result in overvoltage / undervoltage / overcurrent errors _while the power supply is already off_ and also shortly after turning it on (to give the measurements some time to settle).
It should thus not impact our goal of protecting the DUT from actual overvoltages, inverted polarities and overcurrent events, …
> dut_power: implement an error-free grace period after DUT power on

- openapi.yaml
- src/adc.rs
- src/adc/iio/demo_mode.rs
- src/adc/iio/hardware.rs
- src/adc/iio/hardware/channels.rs
- src/adc/iio/test.rs
- src/digital_io/gpio/demo_mode.rs
- src/digital_io/gpio/test.rs
- src/dut_power.rs
- src/main.rs
- src/regulators.rs
- src/system.rs
- src/usb_hub.rs
- web/src/DashboardTac.tsx
This is an alternative to #64, which reads the LXA TAC hardware generation explicitly and sets up the correct ADC channels based on the hardware generation, not based on which channels are available.
This difference is based on a comment in https://github.com/linux-automation/tacd/pull/64#issuecomment-2017537666 , which suggest checking the hardware generation explicitly.
Since both approaches are valid I've decided to open a new PR instead of pushing over the previous one.
Since it would be inconsistent to check the generation explicitly in one location but implicitly in another, this PR also replaces the existing Gen 1 / Gen 2 differentiation in `src/dut_power.rs`.
>  Add LXA TAC hardware generation 3 support (explicit generation detection)

- src/dbus/rauc.rs
- src/dbus/systemd.rs
This fixes new `cargo clippy` errors that complain about unused fields when the `demo_mode` feature is enabled:
```
$ cargo clippy --features=demo_mode --no-default-features
--> src/dbus/rauc.rs:105:9
|
101 | pub struct Rauc {
|            ---- field in this struct
...
105 |     pub primary: Arc<Topic<String>>,
|         ^^^^^^^
|
= note: `-D dead-code` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(dead_code)]`
error: field `action` is never read
--> src/dbus/systemd.rs:55:9
|
54 | pub struct Service {
|            ------- field in this struct
55 |     pub action: Arc<Topic<ServiceAction>>,
|         ^^^^^^
|
= note: `Service` has a derived impl for the trait `Clone`, …
> rauc/systemd: allow struct fields being unread in demo_mode

- src/dbus/rauc.rs
- src/dbus/rauc/update_channels.rs
This makes it so we no longer use deprecated RAUC DBus APIs.
The `Install` -> `InstallBundle` migration is straight forward.
The `Info` -> `InspectBundle` migration is a bit trickier, since RAUC provides the results as nested dictionaries (and also arrays nested inside of that, but we do not currently need any info from those).
This requires a fair bit of type conversions at runtime and the use of some rather funky generics from the `zvariants` crate.
There are probably more elegant solutions to implement the `tacd`-side of this, but for now `zvariant_walk_nested_dicts` gives us something that works.
> rauc: use InstallBundle and InspectBundle instead of deprecated DBus methods

- .codespellrc
- .github/workflows/codespell.yaml
- .github/workflows/tacd-daemon.yaml
- README.md
- deny.toml
- openapi.yaml
- src/adc/iio/hardware.rs
- src/broker/persistence.rs
- src/dbus/rauc.rs
- src/dut_power.rs
- src/http_server/serve_dir.rs
- src/ui.rs
- src/ui/screens/power.rs
- src/ui/widgets.rs
This PR fixes spelling mistakes found by the `codespell` util and adds a CI job to make sure we do not add new typos in the future.
> ci: codespell: add spell checking CI job

- .github/workflows/codespell.yaml
- .github/workflows/tacd-daemon.yaml
- .github/workflows/tacd-webui.yaml
We have been bitten before by upstream `codespell` or `cargo clippy` adding new checks in times of low activity on the repo, resulting in the next pull requests to fail.
Make sure we notice such changes early by running the jobs on a schedule every then and now.
The scheduled time of 20:48 UTC every thursday was chosen by fair dice roll.
> ci: also run jobs on a schedule

- .github/workflows/tacd-daemon.yaml
- .github/workflows/tacd-webui.yaml
There are some GitHub actions we use that have newer versions available.
Update them.
Sadly I've noticed that the [actions-rs](https://github.com/actions-rs/) actions we use are currently unmaintained and archived.
Currently they are not broken, so there is no rush to move to an alternatice, but that may be the case in the future.
> ci: update the GitHub actions used where appropriate

- openapi.yaml
- src/system.rs
- src/ui/screens.rs
- src/ui/screens/diagnostics.rs
- src/ui/screens/setup.rs
When bringup up a new LXA TAC we want to see a few things right away:
- Is the screen straight inside the housing.
- Are all versions (hardware and software) as expected.
- Are the ADC channels calibrated.
- Is the correct update channel activated.
This is easily done with a diagnostics screen. The screen is available via a special button sequence from the setup mode screen.
- Why the setup mode screen?
After bringing up a new TAC the setup mode will be active and should
stay active until the devices arrives at the customer.
This means the diagnostics mode should be reachable via the setup mode
screen.
- Why a special button sequence?
The customer may try to skip the setup process using the buttons on
the device (which is intentionally not possible).
Why means they are likely to make …
> ui: screens: diagnostics: add screen with bringup-relevant information

- web/src/App.test.tsx
- web/src/App.tsx
- web/src/DashboardTac.tsx
- web/src/TacComponents.tsx
- web/src/index.tsx
There are two things in the web interface that look like they can be used to change a piece of configuration but actually can't:
- The "Enabled" checkboxes in the RAUC update channel list.
- The active slot display, also in the RAUC section.
As @a3f (I think) rightfully stated this is a bit confusing to the user,
but actually implementing such actions (in a somewhat safe way) would be quite a lot of work and performing these actions is not something a user would do regularly.
Instead display a notification when one of the actions is requested that looks something like this:
> web: display notifications for actions that can only be done on commandline

- .gitignore
- src/main.rs
- src/motd.rs
This is a refactor of #57 
Not anyone looks at the web interface or the display of the TAC. This gives us a third vector to convey information to the user, by showing messages on ssh login.
Use bind-mounts to put the highly volatile file itself to /var/run and point to it from /etc.
> motd: maintain a /etc/motd file with interesting info about the TAC

- src/motd.rs
The umount/mount construct is more robust when there is e.g. already a `/etc/motd` _file_ or if there is not `/etc/motd` mountpoint yet. The remount method fails in both of these cases.
This two-stage approach was taken from #57. Using remount instead was one of the changes introduced in #77. It looks like neither I nor @KarlK90 tested this change on actual hardware, instead relying only on the demo_mode.
> motd: use explicit umount/mount instead of remount

- src/motd.rs
Looks like the UART is not losing bytes and that there actually *is* a typo here.
Fix that.
> motd: fix typo in greeting

- deny.toml
Since tide did not have a new release since 2021 there is not too much that we can do about this other than move away from tide.
But that is a larger undertaking. Until then I have read through the [advisory][1] and think we should be fine for the time being.
[1]: https://rustsec.org/advisories/RUSTSEC-2023-0086
This should make our [scheduled CI builds](https://github.com/linux-automation/tacd/actions/workflows/tacd-daemon.yaml) succeed again, which would be great.
> cargo deny: acknowledge lexical-core < 1 (a tide dependency) as unsound

- src/ui/display.rs
This was suggested and fixed by `cargo clippy`.
> ui: display: elide explicit lifetimes that are not needed

- Cargo.lock
A routine update inspired by #80. It does not get rid of the security advisory though.
> tacd: update dependencies via cargo update

- .github/workflows/tacd-daemon.yaml
The [actions-rs](https://github.com/actions-rs/toolchain) project is no longer maintained and our workflow runs have produced a lot of warnings due to that for some time now.
Remove our dependency on it by calling `rustup` and `cargo` ourselves. This also makes the CI scripts easier to read in my opinion and easier to reproduce locally since you can just run the same commands as the CI does.
> ci: tacd: remove dependencies on actions-rs GitHub actions

- .github/workflows/tacd-webui.yaml
The build sometimes breaks due to node updates. This would not be much of a problem if the fixes for these breakages did
not break our actual builds with the node versions used in Yocto.
Fix that by using a fixed node version - in this case the one from the Styhead release.
Also make sure the build works on Scarthgap as well.
This should fix the build issue we have seen in this scheduled run: https://github.com/linux-automation/tacd/actions/runs/11845302859
> ci: tacd-webui: use a fixed node version instead of latest

- src/dbus.rs
It [looks like](https://github.com/linux-automation/tacd/actions/runs/12937874780/job/36086772633) `codespell` has once again learned a word that it can spell better than me.
Good bot. Have a cookie: 🍪.
> dbus: typo fix

- src/broker.rs
This fixes a linter error that was added to cargo clippy in release 1.86.0:
clippy::doc-overindented-list-items
> broker: use correct indentation in list in comment

- Cargo.lock
Recent `cargo-deny` job runs have [failed](https://github.com/linux-automation/tacd/actions/runs/14390041898/job/40354751625) due to an Advisory in `tokio` and a yanked version of `url` in our `Cargo.lock`.
Fix both issues by updating the respective dependencies.
> update `tokio` and `url` dependencies to fix cargo deny errors

- src/ui/display.rs
The missing lifetime annotation results in the build showing a warning when compiled using the nightly toolchain:
error: lifetime flowing from input to output with different syntax can be confusing
--> src/ui/display.rs:147:19
|
147 |     pub fn rotate(&mut self) -> DisplayRotated {
|                   ^^^^^^^^^     -------------- the lifetime gets resolved as `'_`
|                   |
|                   this lifetime flows to the output
|
= note: `-D mismatched-lifetime-syntaxes` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(mismatched_lifetime_syntaxes)]`
help: one option is to remove the lifetime for references and use the anonymous lifetime for paths
|
147 |     pub fn rotate(&mut self) -> DisplayRotated<'_> {
| …
> ui: display: prevent mismatched_lifetime_syntaxes compile warning
